micronaut:
  server:
    cors:
      enabled: false

      configurations:
        web:
          allowedOrigins:
            -*
datasources:
  default:
    url: jdbc:postgresql://localhost:5432/book
    driverClassName: org.postgresql.Driver
    username: postgres
    password: 'admin'
    schema-generate: CREATE_DROP
    dialect: POSTGRES
jpa.default.properties.hibernate.hbm2ddl.auto: update
